export default function (data) {
    let en = data
    if(en === null) return '未知地图'
    // 足球
    if (en === 'Triple Dribble') return '三重威胁'
    else if (en === 'Firm Grip') return '牢牢把握'
    else if (en === 'Binary Coding') return '二进制'
    else if (en === 'Sticky Notes') return '便利贴'
    else if (en === 'Turtle Shell') return '坚硬龟壳'
    else if (en === 'Retina') return '视网膜'
    else if (en === 'Sneaky Fields') return '绿荫球场'
    else if (en === 'Sunny Soccer') return '阳光球场'
    else if (en === 'Super Stadium') return '超级体育场'
    else if (en === 'Backyard Bowl') return '后院球场'
    else if (en === 'Pinball Dreams') return '梦幻弹珠'
    else if (en === 'Pinhole Punt') return '精准射门'
    else if (en === 'Field Goal') return '绿茵交锋'
    else if (en === 'Center Stage') return '中心舞台'
    else if (en === 'Center Field') return '中心球场'
    else if (en === 'Super Beach') return '超级海滩'
    else if (en === 'Beach Ball') return '沙滩足球'
    else if (en === 'Post Haste') return '火速出击'
    else if (en === 'Coarse Course') return '粗制滥造'
    else if (en === 'Penalty Kick') return '点球大战'
    else if (en === 'Well Cut') return '带球过人'
    else if (en === 'Warped Beach') return '弯曲海滩'
    else if (en === 'Off the Line') return '超出界外'
    else if (en === 'Hairdryer Treatment') return '场边指导'
    // 金库
    else if (en === 'Safe Zone') return '安全区域'
    else if (en === 'Forks Out') return '迂回岔路'
    else if (en === 'Bridge Too Far') return '遥远的桥'
    else if (en === 'Tornado Ring') return '肆虐龙卷'
    else if (en === 'G.G. Mortuary') return '荒漠废屋'
    else if (en === 'Hot Potato') return '烫手山芋'
    else if (en === 'Twisted Gems') return '变形宝石'
    // 赏金
    else if (en === 'Bull Pen') return '喧闹牛圈'
    else if (en === 'Dry Season') return '酷热地带'
    else if (en === 'Deeper Danger') return '暗潮涌动'
    else if (en === 'Shooting Star') return '神秘流星'
    else if (en === 'Layer Cake') return '夹心蛋糕'
    else if (en === 'Overgrown Canyon') return '蔓生大峡谷'
    else if (en === 'Heat Wave') return '热浪滚滚'
    // 机甲
    else if (en === 'Some Assembly Required') return '等待组装'
    // 热区
    else if (en === 'Open Business') return '开门营业'
    else if (en === 'Mosh Pit') return '冲撞区域'
    else if (en === 'Dueling Beetles') return '甲虫决斗'
    else if (en === 'Parallel Plays') return '平行游戏'
    else if (en === 'Ring of Fire') return '灼热火圈'
    else if (en === 'Double Sided') return '双边并行'
    else if (en === 'Temple of Boom') return '斗域奇兵'
    // 淘汰赛
    else if (en === 'Goldarm Gulch') return '金臂峡谷'
    else if (en === 'Crimewater') return '危险水域'
    else if (en === 'Flaring Phoenix') return '烈焰凤凰'
    else if (en === 'Flowing Springs') return '潺潺溪流'
    else if (en === "Belle's Rock") return '摇滚贝尔'
    else if (en === 'Splash Out') return '大手大脚'
    else if (en === 'Riverside') return '长河堤岸'
    // 篮球
    else if (en === 'Ball Hog') return '首席球迷'

    else return en
}
